# Generated by Django 3.1.1 on 2020-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
